/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_16;

/**
 *
 * @author c.nunes
 */
public class JFrame_Cadastro_de_arma extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Cadastro_de_arma
     */
    public JFrame_Cadastro_de_arma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbl_Modelo_da_Arma = new javax.swing.JLabel();
        jtxtf_campo_modelo_arma = new javax.swing.JTextField();
        jlbl_marca_arma = new javax.swing.JLabel();
        jlbl_calibre = new javax.swing.JLabel();
        jlbl_capacidade = new javax.swing.JLabel();
        jlbl_comprimento_total = new javax.swing.JLabel();
        jlbl_comprimento_cano = new javax.swing.JLabel();
        jlbl_trava_percussor = new javax.swing.JLabel();
        jlbl_trava_gatilho = new javax.swing.JLabel();
        jlbl_acabamento = new javax.swing.JLabel();
        jlbl_peso = new javax.swing.JLabel();
        jckbx_possui = new javax.swing.JCheckBox();
        jckbx_nao_possui = new javax.swing.JCheckBox();
        jckbx_possui_2 = new javax.swing.JCheckBox();
        jckbx_nao_possui_2 = new javax.swing.JCheckBox();
        jtxtf_campo_marca_arma = new javax.swing.JTextField();
        jtxtf_campo_calibre = new javax.swing.JTextField();
        jtxtf_campo_capacidade = new javax.swing.JTextField();
        jtxtf_campo_comprimento_total = new javax.swing.JTextField();
        jtxtf_campo_comprimento_cano = new javax.swing.JTextField();
        jtxtf_campo_acabamento = new javax.swing.JTextField();
        jtxtf_peso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_Modelo_da_Arma.setText("Modelo da arma:");
        jlbl_Modelo_da_Arma.setToolTipText("");

        jtxtf_campo_modelo_arma.setText("modelo arma");
        jtxtf_campo_modelo_arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_campo_modelo_armaActionPerformed(evt);
            }
        });

        jlbl_marca_arma.setText("Marca da arma:");

        jlbl_calibre.setText("Calibre:");

        jlbl_capacidade.setText("Capacidade:");

        jlbl_comprimento_total.setText("Comprimento total:");

        jlbl_comprimento_cano.setText("Comprimento do cano:");

        jlbl_trava_percussor.setText("Trava do Percussor:");

        jlbl_trava_gatilho.setText("Trava do Gatilho:");

        jlbl_acabamento.setText("Acabamento:");

        jlbl_peso.setText("Peso:");

        jckbx_possui.setText("Possui");

        jckbx_nao_possui.setText("Não Possui");

        jckbx_possui_2.setText("Possui");

        jckbx_nao_possui_2.setText("Não Possui");

        jtxtf_campo_marca_arma.setText("marca arma");

        jtxtf_campo_calibre.setText("calibre");
        jtxtf_campo_calibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtf_campo_calibreActionPerformed(evt);
            }
        });

        jtxtf_campo_capacidade.setText("capacidade");

        jtxtf_campo_comprimento_total.setText("comprimento total");

        jtxtf_campo_comprimento_cano.setText("comprimento cano");

        jtxtf_campo_acabamento.setText("acabamento");

        jtxtf_peso.setText("peso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_Modelo_da_Arma)
                            .addComponent(jlbl_marca_arma))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtf_campo_marca_arma, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jtxtf_campo_modelo_arma)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_calibre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_campo_calibre, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_capacidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_campo_capacidade))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_comprimento_total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_campo_comprimento_total))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_comprimento_cano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtf_campo_comprimento_cano))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbl_trava_gatilho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jckbx_possui_2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlbl_trava_percussor)
                                .addGap(18, 18, 18)
                                .addComponent(jckbx_possui)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jckbx_nao_possui)
                            .addComponent(jckbx_nao_possui_2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_acabamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtf_campo_acabamento, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_peso)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_Modelo_da_Arma)
                    .addComponent(jtxtf_campo_modelo_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbl_marca_arma)
                    .addComponent(jtxtf_campo_marca_arma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_calibre)
                    .addComponent(jtxtf_campo_calibre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_capacidade)
                    .addComponent(jtxtf_campo_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_comprimento_total)
                    .addComponent(jtxtf_campo_comprimento_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_comprimento_cano)
                    .addComponent(jtxtf_campo_comprimento_cano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_trava_percussor)
                    .addComponent(jckbx_possui)
                    .addComponent(jckbx_nao_possui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_trava_gatilho)
                    .addComponent(jckbx_possui_2)
                    .addComponent(jckbx_nao_possui_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbl_acabamento)
                    .addComponent(jtxtf_campo_acabamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_peso)
                    .addComponent(jtxtf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtf_campo_modelo_armaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_campo_modelo_armaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_campo_modelo_armaActionPerformed

    private void jtxtf_campo_calibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtf_campo_calibreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtf_campo_calibreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Cadastro_de_arma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Cadastro_de_arma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Cadastro_de_arma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Cadastro_de_arma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Cadastro_de_arma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jckbx_nao_possui;
    private javax.swing.JCheckBox jckbx_nao_possui_2;
    private javax.swing.JCheckBox jckbx_possui;
    private javax.swing.JCheckBox jckbx_possui_2;
    private javax.swing.JLabel jlbl_Modelo_da_Arma;
    private javax.swing.JLabel jlbl_acabamento;
    private javax.swing.JLabel jlbl_calibre;
    private javax.swing.JLabel jlbl_capacidade;
    private javax.swing.JLabel jlbl_comprimento_cano;
    private javax.swing.JLabel jlbl_comprimento_total;
    private javax.swing.JLabel jlbl_marca_arma;
    private javax.swing.JLabel jlbl_peso;
    private javax.swing.JLabel jlbl_trava_gatilho;
    private javax.swing.JLabel jlbl_trava_percussor;
    private javax.swing.JTextField jtxtf_campo_acabamento;
    private javax.swing.JTextField jtxtf_campo_calibre;
    private javax.swing.JTextField jtxtf_campo_capacidade;
    private javax.swing.JTextField jtxtf_campo_comprimento_cano;
    private javax.swing.JTextField jtxtf_campo_comprimento_total;
    private javax.swing.JTextField jtxtf_campo_marca_arma;
    private javax.swing.JTextField jtxtf_campo_modelo_arma;
    private javax.swing.JTextField jtxtf_peso;
    // End of variables declaration//GEN-END:variables
}
